require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MCGAcademyApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'YouTubeSdk', :path => '../node_modules/react-native-youtube-sdk'

  target 'MCGAcademyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MCGAcademyApp-tvOS' do
  # Pods for MCGAcademyApp-tvOS

  target 'MCGAcademyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
